SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE CREW;
TRUNCATE TABLE CREW_MEMBER;
TRUNCATE TABLE IMAGE;
TRUNCATE TABLE MEMBER;
TRUNCATE TABLE SQUAD;
TRUNCATE TABLE SQUAD_MEMBER;

SET REFERENTIAL_INTEGRITY TRUE;

