SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE SQUAD_COMMENT;
TRUNCATE TABLE SQUAD_MEMBER;
TRUNCATE TABLE SQUAD_CATEGORY;
TRUNCATE TABLE SQUAD_PARTICIPANT;
TRUNCATE TABLE ANNOUNCE;
TRUNCATE TABLE SQUAD;

TRUNCATE TABLE CREW_MEMBER;
TRUNCATE TABLE CREW_HASHTAG;
TRUNCATE TABLE CREW_PARTICIPANT;
TRUNCATE TABLE CREW;

TRUNCATE TABLE MEMBER;
TRUNCATE TABLE CATEGORY;
TRUNCATE TABLE HASHTAG;

TRUNCATE TABLE CREW_TOP_MEMBER;

SET REFERENTIAL_INTEGRITY TRUE;

