networks:
  redis-net:
    name: redis-net
  mysql-net:
    name: mysql-net
  monitor-net:
    name: monitor-net

services:
  mysql:
    extends:
      file: ./mysql/docker-compose.yml
      service: mysql

  redis:
    extends:
      file: ./redis/docker-compose.yml
      service: redis

  mysql-exporter:
    extends:
      file: monitor/docker-compose.yml
      service: mysql-exporter

  prometheus:
    extends:
      file: monitor/docker-compose.yml
      service: prometheus

  grafana:
    extends:
      file: monitor/docker-compose.yml
      service: grafana
    depends_on:
      - mysql-exporter
      - prometheus
