name: ci/cd

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  PROJECT_NAME: onsquad

jobs:
  onsquad-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Force Docker API Version
        run: echo 'api.version=1.44' > ~/.docker-java.properties

      - name: Docker Version
        run: |
          docker -v
          docker info

      - name: Make application-dev.yml & application-prod.yml
        run: |
          cd ./src/main/resources
          echo '${{ secrets.APPLICATION_DEV }}' | base64 -d > ./application-dev.yml
          echo '${{ secrets.APPLICATION_PROD }}' | base64 -d > ./application-prod.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -i -s            # run: ./gradlew clean build -Pprofile=ci

      - name: Delivery Executable JAR
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: 'build/libs/*.jar'
          strip_components: 2
          target: /home/${{secrets.USERNAME}}/${{ env.PROJECT_NAME }}

      - name: Execute Jar
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            SOURCE_DIR=$(echo $HOME)/${{ env.PROJECT_NAME }}
            BACKUP_DIR=$SOURCE_DIR/backup
            if [[ ! -d $BACKUP_DIR ]]; then
                mkdir -p $BACKUP_DIR
            fi
            if [[ ! -f $BACKUP_DIR/recycle_bin_backup.txt ]]; then
                echo '' > $BACKUP_DIR/recycle_bin_backup.txt
            fi

            echo "SPRING_PROFILE=${{ secrets.SPRING_PROFILE }}" > $SOURCE_DIR/.env
            echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> $SOURCE_DIR/.env
            
            source $SOURCE_DIR/.env
            curl -s -H "Content-Type: application/json" -d '{"content": "배포가 완료되었습니다. 서버를 재시작합니다."}' $DISCORD_WEBHOOK_URL

            sudo systemctl restart onsquad
